name: Publish to NuGet

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Important for versioning
    
    - name: Fix directory case
      run: |
        mv src/ArcadeDB.Client src/ArcadeDb.Client.tmp || true
        mv src/ArcadeDb.Client.tmp src/ArcadeDb.Client || true
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          9.0.x
          8.0.x
        
    - name: Install semantic-release
      run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/exec
        
    - name: Debug Info
      run: |
        echo "Current directory: $(pwd)"
        echo "Contents of src directory after fix:"
        ls -la src/
        echo "Contents of src/ArcadeDb.Client directory:"
        ls -la src/ArcadeDb.Client/
        echo ".NET Info:"
        dotnet --info
        
    - name: Semantic Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: semantic-release
        
    - name: Restore dependencies
      run: dotnet restore ArcadeDb.Client.sln
      
    - name: Build
      run: dotnet build ArcadeDb.Client.sln --no-restore --configuration Release
      
    - name: Create nupkg directory
      run: mkdir -p nupkgs
      
    - name: Pack Projects
      run: |
        for proj in $(find ./src -name "*.csproj"); do
          echo "Packing $proj"
          dotnet pack "$proj" --no-build --configuration Release --output nupkgs
        done
      
    - name: Push to NuGet
      run: dotnet nuget push "nupkgs/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
