name: Publish to NuGet

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Important for versioning
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Install semantic-release
      run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/exec
        
    - name: Debug Info
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Finding solution file (case sensitive):"
        find . -name "ArcadeDb.Client.sln"
        echo "Finding solution file (case insensitive):"
        find . -iname "arcadedb.client.sln"
        
    - name: Semantic Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: semantic-release
        
    - name: Restore dependencies
      run: dotnet restore ArcadeDb.Client.sln
      
    - name: Build
      run: dotnet build ArcadeDb.Client.sln --no-restore --configuration Release
      
    - name: Create nupkg directory
      run: mkdir -p nupkgs
      
    - name: Pack Projects
      run: |
        # Pack only src projects, not test projects
        find . -path "*/src/*" -name "*.csproj" | while read -r project; do
          echo "Packing $project"
          dotnet pack "$project" --no-build --configuration Release --output nupkgs
        done
      
    - name: Push to NuGet
      run: dotnet nuget push "nupkgs/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
